name=QMC5883PCompass
version=1.0.0
author=zupub
maintainer=zupub
sentence=Library for using QMC5583P series chip boards as a compass.
paragraph=QMC5883P Compass is a Arduino library for using QMC5583P series chip boards as a compass.
category=Sensors
url=https://github.com/zupub/QMC5883PCompass
architectures=*
includes=QMC5883PCompass.h
